apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-server
  namespace: course
  labels:
    app: polling-server
spec:
  selector:
    matchLabels:
      app: polling-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: polling-server
    spec:
      restartPolicy: Always
      imagePullPolicy: IfNotPresent
      containers:
      - image: hitchenwenhao521/polling-backend:5.6
        name: polling-server
        imagePullSecrets:
        - name: myreg
        ports:
        - containerPort: 8080
          name: api
        resources:
          requests:
            cpu: "25m"
            memory: "64M"
          limits:
            cpu: "50m"
            memory: "128M"
       
        env:
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: polling_app
        - name: DB_NAME
          value: root
        - name: DB_PASSWORD
          value: root
        
      
